name: symdesign
channels:
  - conda-forge
  - defaults
dependencies:
  - biopython
  - flametree
  - ipykernel
  - jupyterlab
  - matplotlib
  - mysql-connector-python
  - numba
  - numpy
  - pandas
  - proglog
  - psutil
  - python=3.10
  - pytorch
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - sqlalchemy
  - tqdm
