name: symdesign
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
  - bioconda
dependencies:
  - biopython
  - flametree
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - sqlalchemy
  - psutil
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=10.2
  - hhsuite
  - requests
  - tqdm
  - proglog
# Personally useful though not required
#  - seaborn
#  - numba
#  - jupyterlab
