site_name: symdesign Documentation
repo_url: https://github.com/kylemeador/symdesign

theme:
  name: "material"
  language: en
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: deep purple
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: green
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.instant
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
#    - toc.integrate
    - toc.follow
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            merge_init_into_class: true
            inherited_members: false
            members_order: source
#            show_symbol_type_heading: true  # insider only
#            show_symbol_type_toc: true  # insider only
            show_if_no_docstring: false
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: true
            docstring_options:
              ignore_init_summary: true
            docstring_style: google
            docstring_section_style: list
          paths: [symdesign]
  - gen-files:
      scripts:
        - symdesign/tools/generate_reference_docs.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - search
  - autorefs
nav:
  - Home: README.md
  - User Guide: user_guide.md
  - API reference: reference/

extra_css:
  - css/code_select.css

copyright: Copyright &copy; 2024 Kyle Meador

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kylemeador