#!/bin/bash

if [ ! -e "/home/jlaniado/bin/freesasa/freesasa-2.0/bindings/python/data" ]; then
    ln -s /home/jlaniado/bin/freesasa/freesasa-2.0/tests/data /home/jlaniado/bin/freesasa/freesasa-2.0/bindings/python/
fi
if [ ! -e "/home/jlaniado/bin/freesasa/freesasa-2.0/bindings/python/share" ]; then
    ln -s /home/jlaniado/bin/freesasa/freesasa-2.0/share /home/jlaniado/bin/freesasa/freesasa-2.0/bindings/python/
fi

 python/test.py
